package.json, src/components/editor-panel/editor-panel.tsx, src/styles/global.css
+ build: fix prettier script.
+ feat: added body background-color.
=> fix: ssr for draftjs.

src/components/editor-panel/editor-panel.tsx, src/components/editor-panel/style-controls/index.ts, src/components/editor-panel/toolbar/index.ts, src/components/editor-panel/toolbar/toolbar.tsx
+ fix: renamed InlineCode label to mono.
=> refactor: renamed style-controls to toolbar.

src/components/editor-panel/blocks/modifiers/insert-custom-block.ts, src/components/editor-panel/toolbar/toolbar.tsx
=> fix: added built-in types for toolbar.

src/components/editor-panel/toolbar/toolbar.tsx, src/components/preview-panel/preview-panel.tsx
+ feat: added tooltip for toolbar.
=> feat: added clipboard support.

src/components/preview-panel/latex-containier/latex-container.tsx
https://github.com/SoftMaple/Editor/pull/35#issuecomment-1010771822
=> fix: corrected latex wrapper usage.

src/components/meta/meta.tsx, src/components/preview-panel/latex-containier/dark-wrapper.tsx, src/components/preview-panel/latex-containier/latex-container.style.ts, src/components/preview-panel/latex-containier/latex-wrapper.tsx, src/components/preview-panel/latex-containier/light-wrapper.tsx
=> perf: migrate Highlight.js to Prism.js

src/components/editor-panel/editor-panel.tsx
=> fix: placeholder display bug.

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/FUNDING.yml, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/custom.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, .gitpod.yml, README.md
=> Community Standards

README.md
=> docs: added special thanks to Vercel.

src/components/editor-panel/blocks/math/math-equation.style.ts, src/components/editor-panel/blocks/math/math-equation.tsx, src/components/editor-panel/blocks/modifiers/remove-custom-block.ts
=> fix: type errors.

turbo.json
=> build: fix failure deployment for docs app.

apps/docs/blog/authors.yml
=> fix: corrected author.

turbo.json
=> fix: 500 error?

README.md, docs/docusaurus.config.js
+ docs: moved docs description up.
Fixes #73 .
=> fix: corrected docs editUrl.

apps/editor/.lintstagedrc.js, apps/editor/package.json, apps/insights/.lintstagedrc.js, apps/insights/package.json
=> build: added typecheck pre-commit hook.

README.md, apps/editor/src/components/mobile-view.tsx, apps/editor/src/components/soft-maple-editor.tsx, apps/insights/src/pages/dashboard.tsx, docs/docusaurus.config.js, packages/ui/Header/Header.tsx
Fixes # .
- replaced Vercel with Netlify as the hosting service.
=> feat: replaced Vercel deployment info with Netlify.

apps/insights/src/components/dashboard-tabs/clones-panel/clones-panel.tsx, apps/insights/src/components/dashboard-tabs/views-panel/views-panel.tsx
=> fix(insights): handle empty data.

apps/editor/src/components/soft-maple-editor.tsx
=> fix(editor): added sponsor banner size.

README.md
=> docs: added attention banner in the README.md

.github/.github/workflows/test-md2latex.yml, packages/md2latex/package.json, packages/md2latex/src/md2latex.ts, packages/md2latex/tests/inline.test.ts, pnpm-lock.yaml
=> feat(packages/md2latex): added basic md2latex library.

packages/editor/src/components/core/Editor.tsx, packages/editor/src/stories/Page.stories.ts
=> build(packages/editor): resolved ts errors.
